### ISSUE TITLE
Mailchimp - Missing names for Guide downloads

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#100]
Mailchimp is not showing the names of the people who download the guides.

**Comment by cyrus-gc** [comment]
Fixed. Please check in staging.
Once you subscribed and clicked the link from email, Please update  us here so that we can share the screenshot of mailchimp list of your record and we can close this issue. 
Please clear cookies and use this  "mailanand75@yahoo.com" email Id. 
Note: We have removed this Id in database.
