### ISSUE TITLE
Pending items from the UI update

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#101]
1. On mobile devices, the text area for Family section in profile view mode shows only 2 lines and is not updated with my earlier feedback. All text areas will change in appearance so make sure this is addressed consistently.
2. In the read more modal window, If I use the down arrow or up arrow on my keyboard to scroll, after I reach the end of the scroll, the entire page moves.
3. We should bring back the character counter we had before.
4. On mouse over the navigation arrows next to the theme icons, change their color to orange to be consistent with the button behavior.
5. We need to standardize the use of "optional" across all the panels. Will tell you where to keep and where to remove.

**Comment by cyrus-gc** [comment]
1 . 4th Point is  fixed in this version.
2.  The 1st  &  5th point are Fixed  in earlier version.
3.  The 2nd point is the default  browser behavior.  Even though  there is a solution exists in controlling the browser, it not advice to implement it and  it is not Browser Compatible too .
4.    3rd Point:  For About Me , Partner Expectations , About My Family character counts are displayed in 4 digits. It will not look good  if it displays a 4 Digit Count. Please let  us know your thoughts on this.

Please  verify this in  Staging Server.

**Comment by mailanand75** [comment]
I am not sure if I understand your point about character count. I don't see it as well.

**Comment by cyrus-gc** [comment]
The character count is in place for ABOUT ME, ABOUT MY PARTNER and ABOUT MY FAMILY fields, Please check this in staging.
