### ISSUE TITLE
Bug in tracking profile completion

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#114]
In the production server, I deselected some of the mandatory items in the ABOUT section after completing the profile.

Even after deselecting mandatory information, the video status did not change and the video kept playing. The profile incomplete messages for the ABOUT section did not show up.

**Comment by cyrus-gc** [comment]
Not Reproducible.

**Comment by mailanand75** [comment]
If you can come online on Teamviewer, I can show it to you.

**Comment by mailanand75** [comment]
Tested this feature again. I can see the video no longer plays. However, when we remove the mandatory text fields in the ABOUT section, the orange line and the associated notifications dont appear immediately. They appear only after scrolling away and coming back to the panel. however, mandatory dropdown items are highlighted the moment they are deselected.

**Comment by cyrus-gc** [comment]
This works as per the requirement. Earlier during the phase of development, we had a discussion  on this to display error messages only when the dropdown changes and not for the textboxes. Since we dont want the user to force him to fill in textboxes then and there, we alarm him when he moves to the next section without completing the current section.

**Comment by cyrus-gc** [comment]
Waiting for your updates. Please let me know your thoughts.
