### ISSUE TITLE
Google low-bandwidth page display issues.

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#32]
Google renders a optimized version of our page on smartphones when the bandwidth is poor.

I tried loading our home page on low bandwidth using my phone. Goggle was still able to render our home page without issues and all links were functional.

However, below the footer, Google displayed a series of modal windows and application messages that should not be displayed. You see the issue when you click on the below link from your smartphone browser or even a desktop browser.

http://googleweblight.com/?lite_url=http://www.jodilogik.com

Question: Why is Google displaying the messages below the footer? It shoud have stopped with the footer. This issue also points to the need to build optimized pages to begin with. Please review and let me know.

**Comment by cyrus-gc** [comment]
We have given opacity 0 ( css property) , so that popups will not display in the page. But google has handled it differently and made every popup visible and if we click on JOIN WITH EMAIL,   it will move to that popup( displayed below footer in google version) , it wont be displayed as the original version.  we have no control over this low speed page.
