### ISSUE TITLE
Log In button missing - Refer friend feature

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#6]
This is a Desktop Issue. Will verify for mobile devices separately.

I had highlighted this issue before, here is a screenshot of the home page when a non-member clicks on an email that was sent by a user using the Invite Friend button. The log In button is missing. However, the logIn button appears after a modalwindow message is closed!

![image](https://cloud.githubusercontent.com/assets/12179089/9579577/60f7ef74-5011-11e5-93ed-3baf3b589178.png)

**Comment by cyrus-gc** [comment]
In Refer friend, there will not be a Login button. The friend needs to join using the "Join With Facebook" button since the friend will be automatically "APPROVED" without the admin's consent. If you look closely the URL will have encrypted sender's profile email id and the friend's email id. Using this we will update the sender that the friend has joined Jodi Logik in INVITE FRIENDS section. 

Please let me know your thoughts on this.

**Comment by mailanand75** [comment]
OK. Can you confirm that once the friend signs up using the blue button, and comes back to the home page afterwards, they will see the login button? If yes, we will close this. Please do a verification at your end to make sure the login button is not permanently disabled :)
