### ISSUE TITLE
Blog Image Upload

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#7]
Please enable image upload in blogs. Currently, some securoty issue is blocking new image uploads.

**Comment by cyrus-gc** [comment]
As a default, linux has restricted access (read-only) to the wp-content folder. This is why we see such errors. There is no direct fix to this. We need to follow steps to change the access and reset the access so that external users don't hack the site, edit, change, remove the images. 

Please download PUTTY exe. Enter the host name as jladmin@104.209.44.117 and port as 22 with connection type radio tuned to SSH. Press Enter or click on "Open" button. The pass for this is as given by Mahi. Key in the commands as below or copy and for a paste you need to do a mouse right click on the putty terminal.

sudo chmod -R 777 /var/www/html/wordpress/wp-content

The above command will grant read-write-delete access for the administrator. Now you can add images or update any images to blogs via the wordpress admin login. Once the administrator has completed the wordpress blog updates, the access rights should be reverted to ensure security of the hosted contents. To do this, use the following command in the putty terminal.

sudo chmod -R 755 /var/www/html/wordpress/wp-content

Please verify this and close this issue. Thanks.

**Comment by mailanand75** [comment]
I am able to upload images. However, I am unable to revert to the previous state when image imge upload was not possible. I dont mind keeping this open. I am treating this closed.
