### ISSUE TITLE
Profile update notification bug

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#95]
On June 5th, I made two updates to my profile. On both ocassions, an email went out to the guests even though the second update should have gone only after 24 hours after the first update goes out. This happened with the profile created with mailanand75@yahoo.com on June 5th.

24 hours after, the second update went out once again (as expected).

**Comment by cyrus-gc** [comment]
Any updates in the profile for this user alone , no notification email will be sent to the users in the share list since this is the profile which is circulated as a reference to newly joined users in Jodi Logik. However, the time difference between two notifications triggered from a single user has 24 hours difference. Please test this and close this defect.
